/* SQL SERVER */
LIBNAME TPLDW2 SQLSVR  Datasrc=PL_DW  SCHEMA=anyschema  USER=anyuser PASSWORD="{SAS002}68B2795618???" ; 

/* CONNECTION */
LIBNAME PLEOMADH SQLSVR Datasrc=PLEOMADH SCHEMA=anyschema USER=anyuser PASSWORD="{SAS002}5BC89D???";

